version: "3.8"

services:
  postgres:
    container_name: postgres-db-fastapi
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8

  web:
    container_name: fastapi-app
    build: .
    restart: always
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: bash -c "sleep 20 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
